# Site
title:              ROHAWOLF
bio:                'chapter #2'
description:        "다양한 기록들"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             ko_KR
url:                https://rohawolf.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   rohawolf

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #rohawolf
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
#twitter:            rohawolf
facebook:           roha.park
github-url:         rohawolf
#stackoverflow:     123456/rohawolf   from a "http://stackoverflow.com/users/123456/rohawolf" link
#linkedin:          rohawolf
#xing:              rohawolf
instagram:          rohawolf
#lastfm:            rohawolf
#tumblr:            rohawolf
#medium:            '@rohawolf'
#pinterest:         rohawolf
#foursquare:        rohawolf
steam:              76561198104783984
#dribbble:          rohawolf
#youtube:           rohawolf
#youtube-channel:   channel
#soundcloud:        rohawolf
#weibo:             rohawolf
#flickr:            rohawolf
#codepen:           rohawolf
#keybase:           rohawolf
#xmpp:              rohawolf@server.com
#hackernews:        rohawolf

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
